AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: s3-lambda-dynamodb
Globals:
  Function:
    Timeout: 3

Resources:
  S3Handler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: my-app/
      Handler: app.s3Handler
      Runtime: nodejs12.x
      MemorySize: 128
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref s3LambdaDynamoBucket  # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*

  #Declare an S3 bucket to be created
  s3LambdaDynamoBucket:
    Type: AWS::S3::Bucket


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  S3Handler:
    Description: "S3-Lambda-DynamoDb Lambda Function ARN"
    Value: !GetAtt S3Handler.Arn
  S3HandlerIamRole:
    Description: "Implicit IAM Role created for S3-Lambda-DynamoDb"
    Value: !GetAtt S3HandlerRole.Arn
